### ISSUE TITLE
DS.USERSTATS only returns the User field.

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [CharlesCara/DatastreamDSWS2R#17] opened 2019-10-29 09:21 UTC
I have used this code:
`
myData <- mydsws$snapshotRequest(instrument = "STATS",
                               datatype = c("DS.USERSTATS"),                           
                               requestDate = Sys.Date())
`

The returned data is:

Instrument	User
<chr>	<chr>
STATS	ZEIK339

**Comment by CharlesCara** [comment] 2019-10-29 19:26
Looks like a duplicate of #16.

**Closed as completed by CharlesCara** 2019-10-29 19:26 UTC
Labels: duplicate
